### ISSUE TITLE
Autolayout Compatibility

### ISSUE THREAD

**Issue by ptrkstr** [nighthawk/ASWeekSelectorView#1]
This is a fantastic week selector however the only downside I see is it works through setting frame on first init rather than using autolayout.
Not sure if you're still updating this library but autolayout compatibility would be nice to have.

**Comment by nighthawk** [comment]
Yes, I'm still maintaining this library but didn't yet have a need to add Autolayout capabilities myself, but maybe down the track. Would be good to have indeed. Pull requests are welcome of course!

**Comment by nighthawk** [comment]
The library is now fully compatible with Auto Layout, but you need to adjust the frame in `viewWillLayoutSubviews`. See the main README and the example project.
