### ISSUE TITLE
Fix layout for zoom mode

### ISSUE THREAD

**Issue by carleihar** [nighthawk/ASWeekSelectorView#5]
Hey there, thanks for working on this library! I have noticed that if a user has 'zoom' on in their settings, the library does not play nicely. Would love to have updated support for this feature.

**Comment by nighthawk** [comment]
Thanks. I've just played around with it with the zoom settings from my phone (full screen and 1.2x zoom) and it worked okay - similar to the calendar app.

What specific zoom settings did you notice are making issues? If you have a suggestion for how it should behave in those circumstances, it would help, too.

**Comment by carleihar** [comment]
Oops you know what it might be my own faulty auto-layout issue. Never mind and keep up the good work! :)
